### ISSUE TITLE
Migrate e2e tests from Webdriver to Cypress

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#199]
WIP: #199

(started to experiment with it during Hackergarten meetup in Paris)

Next steps:
- [x] write a simple first test with Cypress and make it run on GitHub Actions and Circle-CI => PR #197.
- [x] convert an existing e2e/acceptance test suite to Cypress => PR #276
- [x] make sure that cypress tests are run from usual npm scripts (e.g. `npm test` and `npm docker:test`) => PR #298
- [x] migrate other tests
- [x] remove bookmarklet test (and others) from webdriver.io tests

**Comment by adrienjoly** [comment]
This could help: [Writing e2e tests using Cypress](https://engineering.hashnode.com/writing-e2e-tests-using-cypress-cjwm1xfxx003osws1dlxp3e5s)

**Comment by adrienjoly** [comment]
Looks like I found our first flaky test occurrence with Cypress: https://github.com/openwhyd/openwhyd/pull/306/checks?check_run_id=542061609

```
  Openwhyd

    ✓ should allow user to login (4864ms)

    1) should allow a user to add a track

    ✓ should allow a visitor to sign up and follow the onboarding process (9606ms)

    ✓ should allow user to re-add a track into a playlist (4280ms)

    ✓ should allow user to manipulate comments (1977ms)

    ✓ should allow users to search external tracks (2302ms)


  5 passing (32s)
  1 failing

  1) Openwhyd should allow a user to add a track:
     CypressError: Timed out retrying: Expected to find content: 'your tracks' but never did.
```

(Re-running the workflow made the test pass.)

=> Could this ~flakiness be caused by the stress that adding the "Docker / test" workflow may have put on our GitHub Actions machine(s)?
