### ISSUE TITLE
Finish/fix migration to Mongodb 3

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#236]
## TODO

- [x] fix circular dependencies (see warnings included below)
- [x] DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
- [x] in calls to `find()`: `fields:` --> `projection:`
- [ ] remove remaining references to deprecated functions (e.g. `count()` and `remove()`)

Refs:

- [node-mongodb-native/CHANGES_3.0.0.md at 3.6 · mongodb/node-mongodb-native](https://github.com/mongodb/node-mongodb-native/blob/3.6/CHANGES_3.0.0.md)
- https://mongodb.github.io/node-mongodb-native/3.6/api/
- [fix: Improve use of MongoDB 3](https://github.com/openwhyd/openwhyd/pull/237) (wip)
- notes from [fix(mongodb): prevent "db.collections is not a function" error by adrienjoly · Pull Request #232 · openwhyd/openwhyd](https://github.com/openwhyd/openwhyd/pull/232)

**Comment by adrienjoly** [comment]
After migrating to mongodb client v3 (see PRs #356 and #255, running in production for 2 days), we're getting the following warnings (and probably many others):

```
❌ Error -- Sun, 08 Nov 2020 13:49:17 GMT (node:4241) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
❌ Error -- Sun, 08 Nov 2020 13:49:17 GMT (node:4241) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
❌ Error -- Sun, 08 Nov 2020 13:49:17 GMT (node:4241) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
❌ Error -- Sun, 08 Nov 2020 13:49:17 GMT (node:4241) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
```

...as spotted in https://github.com/openwhyd/openwhyd/runs/1370367735#step:10:40.

**Comment by adrienjoly** [comment]
Done in #630.
