### ISSUE TITLE
very old posts featured in hot tracks

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#718]
**Describe the bug**

Hot tracks include several tracks that were posted back in 2021, 2019, and even 2014! Which is weird for a "hot tracks" section.

More importantly, some of these hot tracks were deleted from YouTube since then => did someone like and/or repost these posts recently (if so: why?), or is there a bug in the way scores are computed?

<img width="912" alt="image" src="https://github.com/openwhyd/openwhyd/assets/531781/9453331e-8c7f-453a-84cd-947bcdc554a1">

**Expected behavior**

Hot tracks should generally still be playable on YouTube, and be posted recently.

Thanks to Stefanos for reporting this.

## TODO before closing

- [x] update hot tracks so more recent tracks are shown
- [ ] update the relative scoring (i.e. arrows that show when scores have gone up or down), or delete it
- [ ] remove old code

**Comment by adrienjoly** [comment]
[JSON export](https://openwhyd.org/hot?format=json) corresponding to the screenshot above:

```json
{
  "hasMore": { "skip": 20 },
  "tracks": [
    {
      "_id": "53f5d7af7b4e770b172679bc",
      "uId": "52e2620f7e91c862b2b3f66a",
      "uNm": "Rien",
      "text": "",
      "pl": { "name": "Balkan Beat Gypsy #03", "id": 144 },
      "name": "Haris Pilton - Gypsy Partizans (2013)",
      "eId": "/sc/undefined",
      "img": "https://i1.sndcdn.com/artworks-000047093292-y6wbnv-large.jpg?e76cf77",
      "nbP": 958,
      "lov": [
        "53da584ce04b7b4fca7cf528",
        "518b5a447e91c862b2adea1a",
        "6485e598d1b1033fa650d66b"
      ],
      "nbR": 213,
      "score": 900,
      "nbL": 19,
      "prev": 900,
      "trackId": "54bf88e3e04b7b4fca82c18f",
      "rankIncr": 0,
      "trackUrl": "//soundcloud.com/undefined",
      "isLoved": false
    },
    {
      "_id": "64f2aefba083ed4627cc2b80",
      "uId": "5438c677e04b7b4fca7fb4f3",
      "uNm": "jacques mercier",
      "text": "",
      "name": "Marianne Faithfull - As Tears Go By (Official Lyric Video)",
      "eId": "/yt/-efIjZ_1yQg",
      "ctx": "bk",
      "pl": { "id": 4, "name": "vieux pop" },
      "img": "https://i.ytimg.com/vi/-efIjZ_1yQg/default.jpg",
      "nbP": 1,
      "nbR": 7,
      "score": 500,
      "nbL": 2,
      "prev": 500,
      "trackId": "5e89f0bcd24d2b59d25a9b50",
      "rankIncr": 0,
      "trackUrl": "//youtube.com/watch?v=-efIjZ_1yQg",
      "isLoved": false
    },
    {
      "_id": "64f8ac15f3b1cb8d4422e072",
      "uId": "5edbd60cdadc93b520a93bfb",
      "uNm": "Phil72 Le Mans",
      "text": "Field Medic – light is gone 2",
      "name": "Field Medic - \"you deserve attention\" (Official Audio)",
      "eId": "/yt/M_EeY9f-vqw",
      "ctx": "bk",
      "pl": { "id": 150, "name": "Phil151 2023" },
      "img": "https://i.ytimg.com/vi/M_EeY9f-vqw/default.jpg",
      "src": {
        "id": "https://www.youtube.com/watch?v=M_EeY9f-vqw&list=OLAK5uy_mi04TykEgMAT2bMAF_Hn9YVPbYTMKOTS8&index=3",
        "name": "Field Medic - &quot;you deserve attention&quot; (Official Audio) - YouTube"
      },
      "nbP": 2,
      "nbR": 4,
      "score": 400,
      "nbL": 0,
      "prev": 200,
      "trackId": "64f427cdb7a6f713813f156a",
      "rankIncr": -200,
      "trackUrl": "//youtube.com/watch?v=M_EeY9f-vqw",
      "isLoved": false
    },
    {
      "_id": "64e7757367d420f43863af2b",
      "uId": "5361647f71eaec19b57037e4",
      "uNm": "Gérard Duquesnoy",
      "text": "",
      "name": "Elton John - Nikita - 1985",
      "eId": "/yt/3XI1cOgzbYI",
      "ctx": "bk",
      "pl": {
        "id": 1257,
        "name": "English Songs   -     (  All kinds of music except jazz and similar  )"
      },
      "img": "https://i.ytimg.com/vi/3XI1cOgzbYI/default.jpg",
      "nbP": 3,
      "nbR": 3,
      "score": 300,
      "nbL": 0,
      "prev": 300,
      "trackId": "64e96b8e56db4f4b4d13634e",
      "rankIncr": 0,
      "trackUrl": "//youtube.com/watch?v=3XI1cOgzbYI",
      "isLoved": false
    },
    {
      "_id": "644d61210767b76a40dbbc2d",
      "uId": "555361d14bf212908fb2b6dc",
      "uNm": "Shannon J",
      "text": "",
      "name": "ROZES - I'll Follow (Official Audio)",
      "eId": "/yt/FXaeV3qi8B8",
      "ctx": "bk",
      "pl": { "id": 43, "name": "Longboard/Roadtrip" },
      "img": "https://i.ytimg.com/vi/FXaeV3qi8B8/default.jpg",
      "nbP": 2,
      "nbR": 3,
      "score": 300,
      "nbL": 0,
      "prev": 300,
      "trackId": "644e7853d1b1033fa61277db",
      "rankIncr": 0,
      "trackUrl": "//youtube.com/watch?v=FXaeV3qi8B8",
      "isLoved": false
    },
    {
      "_id": "5ff67c0d08ced3543db05081",
      "eId": "/yt/NfrkIdpvahY",
      "nbR": 3,
      "nbP": 5,
      "nbL": 0,
      "pId": "5ff5cb8fa6ee3b7702829675",
      "name": "Patsy Cline - Crazy",
      "img": "https://i.ytimg.com/vi/NfrkIdpvahY/default.jpg",
      "score": 300,
      "prev": 300,
      "trackUrl": "//youtube.com/watch?v=NfrkIdpvahY",
      "isLoved": false
    },
    {
      "_id": "591409492e6aba274f2b8de2",
      "uId": "518b66407e91c862b2adeb3e",
      "uNm": "Yoavmis",
      "text": "",
      "pl": { "name": "the sounds of the roads", "id": 59 },
      "name": "Iggy Pop & Goran Bregovic - In The Death Car (Arizona Dream)",
      "eId": "/yt/_Zv_lBLU5Vo",
      "ctx": "bk",
      "img": "https://i.ytimg.com/vi/_Zv_lBLU5Vo/default.jpg",
      "nbP": 87,
      "nbR": 16,
      "lov": ["52d94c7d7e91c862b2b33d54"],
      "score": 300,
      "nbL": 4,
      "prev": 0,
      "trackId": "5914142a98267ba4b34b85b6",
      "rankIncr": -300,
      "trackUrl": "//youtube.com/watch?v=_Zv_lBLU5Vo",
      "isLoved": false
    },
    {
      "_id": "5c3f721ca03c1e20cf0996d1",
      "uId": "548332e0e04b7b4fca818ec3",
      "uNm": "MAUREL",
      "text": "",
      "name": "Djinji Dinji Bubamara - Emir Kusturica",
      "eId": "/yt/5NpPRrlMhp0",
      "ctx": "bk",
      "img": "https://i.ytimg.com/vi/5NpPRrlMhp0/default.jpg",
      "src": {
        "id": "https://www.youtube.com/watch?v=5NpPRrlMhp0",
        "name": "Djinji Dinji Bubamara - Emir Kusturica - YouTube"
      },
      "nbP": 116,
      "nbR": 18,
      "lov": ["569b7e374bf212908fb69312"],
      "score": 300,
      "nbL": 2,
      "prev": 300,
      "trackId": "527505f77e91c862b2b0cab4",
      "rankIncr": 0,
      "trackUrl": "//youtube.com/watch?v=5NpPRrlMhp0",
      "isLoved": false
    },
    {
      "_id": "51f6d8910a44568821025298",
      "eId": "/yt/KeKPkGflDB4",
      "img": "https://i.ytimg.com/vi/KeKPkGflDB4/0.jpg",
      "name": "You Never Can Tell (Lyrics) - Chuck Berry",
      "nbP": 106,
      "order": 77,
      "pl": { "name": "sixties", "id": 0 },
      "text": "1964 r&r",
      "uId": "51ec46ff7e91c862b2af59c9",
      "uNm": "Benny ",
      "nbR": 36,
      "lov": ["518b5a447e91c862b2adea1a"],
      "score": 300,
      "nbL": 5,
      "prev": 0,
      "trackId": "51f6d8917e91c862b2af790b",
      "rankIncr": -300,
      "trackUrl": "//youtube.com/watch?v=KeKPkGflDB4",
      "isLoved": false
    },
    {
      "_id": "64f98634f3b1cb8d4422e091",
      "uId": "5f982b08bdb995520b561f0a",
      "uNm": "Disquovery",
      "text": "",
      "name": "Savant - Nitegeist",
      "eId": "/yt/erflbdKYDfs",
      "ctx": "bk",
      "pl": { "id": 351, "name": "Entre Carthago, Chassol et Perturbator" },
      "img": "https://i.ytimg.com/vi/erflbdKYDfs/default.jpg",
      "src": {
        "id": "https://www.youtube.com/watch?v=erflbdKYDfs",
        "name": "(773) Nitegeist - YouTube"
      },
      "order": 8,
      "nbP": 1,
      "nbR": 2,
      "score": 200,
      "nbL": 0,
      "trackId": "64f9a29cb7a6f713818d1401",
      "rankIncr": null,
      "trackUrl": "//youtube.com/watch?v=erflbdKYDfs",
      "isLoved": false
    },
    {
      "_id": "64f98a61f3b1cb8d4422e093",
      "uId": "5f982b08bdb995520b561f0a",
      "uNm": "Disquovery",
      "text": "",
      "name": "Rale Daver - Mecha Church",
      "eId": "/yt/B2IkmIRZBk0",
      "ctx": "bk",
      "pl": { "id": 351, "name": "Entre Carthago, Chassol et Perturbator" },
      "img": "https://i.ytimg.com/vi/B2IkmIRZBk0/default.jpg",
      "src": {
        "id": "https://www.youtube.com/watch?v=B2IkmIRZBk0",
        "name": "(773) Rale Daver - Mecha Church - YouTube"
      },
      "order": 10,
      "nbP": 1,
      "nbR": 2,
      "score": 200,
      "nbL": 0,
      "trackId": "64f9a224b7a6f713818d0e2b",
      "rankIncr": null,
      "trackUrl": "//youtube.com/watch?v=B2IkmIRZBk0",
      "isLoved": false
    },
    {
      "_id": "64f98208f3b1cb8d4422e089",
      "uId": "5f982b08bdb995520b561f0a",
      "uNm": "Disquovery",
      "text": "",
      "name": "Trupe Chá de Boldo - Diacho",
      "eId": "/yt/Cq2cknBUXBk",
      "ctx": "bk",
      "pl": { "id": 351, "name": "Entre Carthago, Chassol et Perturbator" },
      "img": "https://i.ytimg.com/vi/Cq2cknBUXBk/default.jpg",
      "src": {
        "id": "https://www.youtube.com/watch?v=Cq2cknBUXBk",
        "name": "(773) &quot;Diacho&quot; - Trupe Chá de Boldo - YouTube"
      },
      "nbP": 2,
      "nbR": 2,
      "order": 2,
      "score": 200,
      "nbL": 0,
      "trackId": "64f985c6b7a6f713818b9cdc",
      "rankIncr": null,
      "trackUrl": "//youtube.com/watch?v=Cq2cknBUXBk",
      "isLoved": false
    },
    {
      "_id": "64f98411f3b1cb8d4422e08b",
      "uId": "5f982b08bdb995520b561f0a",
      "uNm": "Disquovery",
      "text": "",
      "name": "(773) GARGÄNTUA - IMMORAL & ILLÉGAL (OFFICIAL VIDEO)",
      "eId": "/yt/Lssp90G-bN0",
      "ctx": "bk",
      "pl": { "id": 351, "name": "Entre Carthago, Chassol et Perturbator" },
      "img": "https://i.ytimg.com/vi/Lssp90G-bN0/default.jpg",
      "src": {
        "id": "https://www.youtube.com/watch?v=Lssp90G-bN0",
        "name": "(773) GARGÄNTUA - IMMORAL &amp; ILLÉGAL (OFFICIAL VIDEO) - YouTube"
      },
      "lov": ["518b5a447e91c862b2adea1a"],
      "nbP": 1,
      "nbR": 2,
      "order": 6,
      "score": 200,
      "nbL": 1,
      "trackId": "64f98488b7a6f713818b85e7",
      "rankIncr": null,
      "trackUrl": "//youtube.com/watch?v=Lssp90G-bN0",
      "isLoved": false
    },
    {
      "_id": "64f86638e8d12a01251add28",
      "uId": "518b5a447e91c862b2adea1a",
      "uNm": "Israel Lindenbaum",
      "text": "",
      "name": "THE SHADOWS Apache",
      "eId": "/yt/huLaUR8Hx5c",
      "ctx": "bk",
      "pl": {
        "id": 3,
        "name": "swing/soul/blues/jazz/down beat/oldies/folk/funk"
      },
      "img": "https://i.ytimg.com/vi/huLaUR8Hx5c/default.jpg",
      "lov": ["544c39c3e04b7b4fca803438"],
      "score": 200,
      "nbP": 0,
      "nbL": 1,
      "nbR": 2,
      "trackId": "64f8d17cb7a6f7138181bde1",
      "rankIncr": null,
      "trackUrl": "//youtube.com/watch?v=huLaUR8Hx5c",
      "isLoved": false
    },
    {
      "_id": "64f84b58e8d12a01251add18",
      "uId": "544c39c3e04b7b4fca803438",
      "uNm": "Stefanos",
      "text": "",
      "name": "The Cars - Tonight She Comes (Official Music Video)",
      "eId": "/yt/XlfH1SR0mnc",
      "ctx": "bk",
      "img": "https://i.ytimg.com/vi/XlfH1SR0mnc/default.jpg",
      "nbP": 1,
      "nbR": 2,
      "score": 200,
      "nbL": 0,
      "trackId": "64f868a0b7a6f713817c27e5",
      "rankIncr": null,
      "trackUrl": "//youtube.com/watch?v=XlfH1SR0mnc",
      "isLoved": false
    },
    {
      "_id": "64f850c1e8d12a01251add1a",
      "uId": "544c39c3e04b7b4fca803438",
      "uNm": "Stefanos",
      "text": "",
      "name": " Eleanor Underhill - Bringing Down The Ghosts (Official Music Video)",
      "eId": "/yt/suuHNWtJjgM",
      "ctx": "bk",
      "img": "https://i.ytimg.com/vi/suuHNWtJjgM/default.jpg",
      "nbP": 1,
      "nbR": 2,
      "score": 200,
      "nbL": 0,
      "trackId": "64f867a6b7a6f713817c1c8a",
      "rankIncr": null,
      "trackUrl": "//youtube.com/watch?v=suuHNWtJjgM",
      "isLoved": false
    },
    {
      "_id": "64f85684e8d12a01251add1c",
      "uId": "544c39c3e04b7b4fca803438",
      "uNm": "Stefanos",
      "text": "",
      "name": "Clementine Valentine - Selenelion",
      "eId": "/yt/P2wOOy9xwxA",
      "ctx": "bk",
      "img": "https://i.ytimg.com/vi/P2wOOy9xwxA/default.jpg",
      "nbP": 2,
      "nbR": 2,
      "score": 200,
      "nbL": 0,
      "trackId": "64f86773b7a6f713817c1987",
      "rankIncr": null,
      "trackUrl": "//youtube.com/watch?v=P2wOOy9xwxA",
      "isLoved": false
    },
    {
      "_id": "64f76510e8d12a01251adcf0",
      "uId": "5356db0471eaec19b56fe9ff",
      "uNm": "Muriel (µµ)",
      "text": "",
      "name": "ARCHIVE - VICE (Official Music Video)",
      "eId": "/yt/KjRwgP25v6s",
      "ctx": "bk",
      "pl": { "id": 0, "name": "Pop / New Wave" },
      "img": "https://i.ytimg.com/vi/KjRwgP25v6s/default.jpg",
      "src": {
        "id": "https://www.youtube.com/watch?v=KjRwgP25v6s",
        "name": "ARCHIVE - VICE (Official Music Video) - YouTube"
      },
      "nbP": 1,
      "nbR": 2,
      "score": 200,
      "nbL": 0,
      "trackId": "64f823a5b7a6f71381784d33",
      "rankIncr": null,
      "trackUrl": "//youtube.com/watch?v=KjRwgP25v6s",
      "isLoved": false
    },
    {
      "_id": "64f78854e8d12a01251adcf2",
      "uId": "5356db0471eaec19b56fe9ff",
      "uNm": "Muriel (µµ)",
      "text": "",
      "name": "Slowdive - Prayer remembered",
      "eId": "/yt/XvMLeQCU8ew",
      "ctx": "bk",
      "pl": { "id": 3, "name": "Electro / Chill" },
      "img": "https://i.ytimg.com/vi/XvMLeQCU8ew/default.jpg",
      "src": {
        "id": "https://www.youtube.com/watch?v=XvMLeQCU8ew",
        "name": "prayer remembered - YouTube"
      },
      "lov": ["518b5a447e91c862b2adea1a"],
      "nbP": 1,
      "score": 200,
      "nbL": 1,
      "nbR": 2,
      "trackId": "64f82388b7a6f71381784b8f",
      "rankIncr": null,
      "trackUrl": "//youtube.com/watch?v=XvMLeQCU8ew",
      "isLoved": false
    },
    {
      "_id": "64f6c57b8e17e2c0a0aab36c",
      "uId": "5438c677e04b7b4fca7fb4f3",
      "uNm": "jacques mercier",
      "text": "",
      "name": "PALLADIO - Allegretto - Karl Jenkins",
      "eId": "/yt/hViPSRHyU0Y",
      "ctx": "bk",
      "pl": { "id": 6, "name": "classique" },
      "img": "https://i.ytimg.com/vi/hViPSRHyU0Y/default.jpg",
      "nbP": 1,
      "nbR": 2,
      "score": 200,
      "nbL": 0,
      "trackId": "64f8236ab7a6f71381784a16",
      "rankIncr": null,
      "trackUrl": "//youtube.com/watch?v=hViPSRHyU0Y",
      "isLoved": false
    }
  ]
}
```

**Comment by adrienjoly** [comment]
## First track => first problem 😅

Its `eId` is `/sc/undefined`, which is probably the `eId` assigned to most tracks added from SoundCloud since this issue: https://github.com/openwhyd/openwhyd/issues/614.

This may explain why that track has so many plays: it actually represent several tracks that end up with the same faulty `eId`.

**Comment by adrienjoly** [comment]
## New version of the ranking

Based on number of (re)posts and likes, over the last 7 days.

<img width="821" alt="image" src="https://github.com/openwhyd/openwhyd/assets/531781/bbd9dde0-f61e-4aef-b78a-2d0a2f3fedc4">

**Comment by adrienjoly** [comment]
## Before making sure that the earlier user is featured

![image](https://github.com/openwhyd/openwhyd/assets/531781/2c0ecbfb-66c7-4e08-897f-71b065beb030)


## After making sure that the earlier user is featured

Change: https://github.com/openwhyd/openwhyd/commit/3a7a718cbf5dd8a7d9ab94cd3bae8a447f59e8a1

![image](https://github.com/openwhyd/openwhyd/assets/531781/46ab96f8-a395-4af1-8d5f-5cb97c1082aa)
